export const products = [
    {
      id : 1,
      name: "Smartphone",
      brand: "Galaxy X1",
      price: 799,
      description: "6.7-inch display, 128GB storage, 5G capable",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 2,
      name: "Laptop",
      brand: "SuperTech Pro 15",
      price: 1299,
      description: "15.6-inch, 16GB RAM, 512GB SSD",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 3,
      name: "Wireless Earbuds",
      brand: "SoundBlast E100",
      price: 149,
      description: "Noise cancellation, 20 hours battery life",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 4,
      name: "Smartwatch",
      brand: "TimeMax S4",
      price: 249,
      description: "GPS, heart-rate monitor, water-resistant",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 5,
      name: "4K TV",
      brand: "UltraView 50\"",
      price: 499,
      description: "50-inch, 4K UHD, HDR10+",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 6,
      name: "Gaming Console",
      brand: "PlayMaster X",
      price: 499,
      description: "1TB storage, 4K gaming",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 7,
      name: "Bluetooth Speaker",
      brand: "BeatBoom 360",
      price: 99,
      description: "360° sound, waterproof",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 8,
      name: "Digital Camera",
      brand: "PixelShot Z7",
      price: 899,
      description: "24MP, 4K video recording",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 9,
      name: "Tablet",
      brand: "TechSlate T10",
      price: 599,
      description: "10.5-inch display, 256GB storage, 8GB RAM",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 10,
      name: "Fitness Tracker",
      brand: "FitFlex F5",
      price: 119,
      description: "Heart-rate monitor, sleep tracking, GPS",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 11,
      name: "Smart Home Hub",
      brand: "HomeSync Pro",
      price: 199,
      description: "Voice control, smart device integration",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 12,
      name: "Action Camera",
      brand: "AdventureCam 4K",
      price: 299,
      description: "4K video, waterproof, image stabilization",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 13,
      name: "Drone",
      brand: "SkyWing X200",
      price: 899,
      description: "4K camera, 30-minute flight time, GPS",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 14,
      name: "Portable Charger",
      brand: "PowerPack 20000",
      price: 59,
      description: "20,000mAh, fast charging, dual USB ports",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 15,
      name: "VR Headset",
      brand: "VirtualPlay VR2",
      price: 349,
      description: "4K display, 110° FOV, motion tracking",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 16,
      name: "E-Reader",
      brand: "ReadMate S8",
      price: 179,
      description: "8-inch display, 32GB storage, glare-free screen",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 17,
      name: "Electric Scooter",
      brand: "ZoomRide X3",
      price: 799,
      description: "15-mile range, 25 mph top speed, foldable",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 18,
      name: "Smart Thermostat",
      brand: "EcoTemp 3",
      price: 249,
      description: "Energy saving, remote control, programmable",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 19,
      name: "Coffee Maker",
      brand: "BrewPro 500",
      price: 149,
      description: "12-cup, programmable, thermal carafe",
      image : "https://picsum.photos/300/200",
    },
    {
      id : 20,
      name: "Air Purifier",
      brand: "CleanAir A7",
      price: 299,
      description: "HEPA filter, quiet operation, 5-speed settings",
      image : "https://picsum.photos/300/200",
    }
  ];
  